#

In [2]:
import numpy as np
import pandas as pd

In [66]:
# copied from as2.py
OPCODES = {
    "nop": 0,
    "+": 1,
    "-": 2,
    "*": 3,
    "/": 4,
    "%": 5,
    ">>": 6,
    "<<": 7,
    "~": 8,
    ">": 9,
    "<": 10,
    ">=": 11,
    "<=": 12,
    "==": 13,
    "!=": 14,
    "jump": 15,
    "jump_imm": 16,
    "call": 17,  # probably don't need this one
    "call_imm": 18,
    "btrue": 19,
    "btrue_imm": 20,
    "bfalse": 21,
    "bfalse_imm": 22,
    "return": 23,
    ";": 23,  # alias
    "load_module": 24,
    "extern_call": 25,
    "loadword": 26,
    "@": 26,  # alias
    "storeword": 27,
    "!": 27,  # alias
    "push_imm": 28,
    "dup": 29,
    "swap": 30,
    "drop": 31,
    "over": 32,
    "rot": 33,
    "dup2": 34,
    "swap2": 35,
    "over2": 36,
    "drop2": 37,  # why?
    "rpush": 38,
    ">r": 38,  # alias
    "rpop": 39,
    "r>": 39,  # alias
    "rcopy": 40,
    "r@": 40,  # alias
    "inc": 41,
    "dec": 42,
    "rcopy2": 43,
    "loadbyte": 44,
    "@b": 44,
    "storebyte": 45,
    "!b": 45,
    "pick": 46,
    "and": 47,
    "or": 48,
    "xor": 49,
    "lsr": 50,
}

# invert the dict
ops = {}
for k, v in op2id.items():
    ops[v] = k

In [74]:
df = pd.read_csv("running_opcodes.csv", names=["opcode"])
df["opcode_name"] = df.apply(lambda r: ops[int(r["opcode"])], axis=1)

In [75]:
df

       opcode  opcode_name
0          18     call_imm
1          28     push_imm
2          26            @
3          28     push_imm
4          25  extern_call
...       ...          ...
26859      26            @
26860      28     push_imm
26861      25  extern_call
26862      23            ;
26863      23            ;

[26864 rows x 2 columns]

In [76]:
# create a new df where the columns are values in a rolling window of winsize
def rolling_to_df(df, winsize):
    rol = df.rolling(winsize)
    rows = []
    for window in rol:
        ops = window.reset_index(drop=True)["opcode_name"]
        rows.append(ops)
    return pd.DataFrame(rows)

In [77]:
def markov_count(df, winsize):
    win = rolling_to_df(df, winsize)
    return win.groupby(list(range(winsize)), as_index=False).value_counts().sort_values(by="count", ascending=False)

In [78]:
pd.set_option('display.max_rows', 500)

In [85]:
markov_count(df, 5)

               0            1            2            3            4  count
113     call_imm     call_imm     push_imm            ;            *   1057
122     call_imm     push_imm            ;            *     push_imm    876
183     push_imm            ;            *     push_imm            +    876
23             +     push_imm            +            ;            @    800
177     push_imm            +     push_imm            +            ;    800
33             ;            *     push_imm            +     push_imm    800
11             *     push_imm            +     push_imm            +    800
156          inc           >r     jump_imm       rcopy2            >    664
212           r>          inc           >r     jump_imm       rcopy2    664
76            >r     jump_imm       rcopy2            >   bfalse_imm    664
161     jump_imm       rcopy2            >   bfalse_imm           r@    653
61             ;           r>          inc           >r     jump_imm    456
15             +            ;            @            <   bfalse_imm    400
220       rcopy2            >   bfalse_imm           r@     call_imm    400
215           r@     call_imm     call_imm     push_imm            ;    400
171     push_imm            +            ;            @            <    400
221       rcopy2            >   bfalse_imm           r@     push_imm    264
9              *            +     push_imm            +           @b    257
121     call_imm     push_imm            ;            *            +    257
31             ;            *            +     push_imm            +    257
182     push_imm            ;            *            +     push_imm    257
24             +     push_imm            +           @b            ;    257
146          dup     call_imm     push_imm            ;           ==    256
125     call_imm     push_imm            ;           ==   bfalse_imm    256
41             ;           >r     call_imm     push_imm            *    256
118     call_imm     push_imm            *         swap     push_imm    256
60             ;           r>          dup     call_imm     push_imm    256
116     call_imm         over         over     call_imm     call_imm    256
72             >   bfalse_imm           r@     push_imm            @    256
75            >r     call_imm     push_imm            *         swap    256
97            @b            ;           >r     call_imm     push_imm    256
81             @     call_imm         over         over     call_imm    256
112   bfalse_imm           r@     push_imm            @     call_imm    256
230         swap     push_imm            *         swap            ;    256
218           r@     push_imm            @     call_imm         over    256
226         swap            ;           r>          dup     call_imm    256
14             *         swap     push_imm            *         swap    256
12             *         swap            ;           r>          dup    256
191     push_imm            @     call_imm         over         over    256
175     push_imm            +           @b            ;           >r    256
21             +           @b            ;           >r     call_imm    256
211           r>          dup     call_imm     push_imm            ;    256
170     push_imm            *         swap     push_imm            *    256
168     push_imm            *         swap            ;           r>    256
163         over         over     call_imm     call_imm     push_imm    256
162         over     call_imm     call_imm     push_imm            ;    256
93             @           r@     call_imm     call_imm     push_imm    200
228         swap     call_imm     call_imm     push_imm            ;    200
216           r@     call_imm          dup          dup     call_imm    200
70             >   bfalse_imm           r@     call_imm          dup    200
78             @            <   bfalse_imm         drop            ;    200
79             @            <   bfalse_imm           r>          inc    200
64             <   bfalse_imm           r>          inc           >r    200
107   bfalse_imm           r>          inc           >r     jump_imm    200
96             @         swap     call_imm     call_imm     push_imm    200
102   bfalse_imm         drop            ;           r>          inc    200
147          dup          dup     call_imm     call_imm     push_imm    200
109   bfalse_imm           r@     call_imm     call_imm     push_imm    200
110   bfalse_imm           r@     call_imm          dup          dup    200
173     push_imm            +            ;            @         swap    200
172     push_imm            +            ;            @           r@    200
135         drop            ;           r>          inc           >r    200
144          dup     call_imm     call_imm     push_imm            ;    200
69             >   bfalse_imm           r@     call_imm     call_imm    200
115     call_imm          dup          dup     call_imm     call_imm    200
43             ;            @            <   bfalse_imm           r>    200
17             +            ;            @         swap     call_imm    200
62             <   bfalse_imm         drop            ;           r>    200
45             ;            @         swap     call_imm     call_imm    200
44             ;            @           r@     call_imm     call_imm    200
42             ;            @            <   bfalse_imm         drop    200
16             +            ;            @           r@     call_imm    200
159     jump_imm            ;           r>          inc           >r    180
39             ;           ==   bfalse_imm         drop         drop    180
137         drop         drop         drop     jump_imm            ;    180
138         drop         drop     jump_imm            ;           r>    180
140         drop     jump_imm            ;           r>          inc    180
187     push_imm            ;           ==   bfalse_imm         drop    180
103   bfalse_imm         drop         drop         drop     jump_imm    180
67            ==   bfalse_imm         drop         drop         drop    180
196     push_imm            @     push_imm  extern_call            ;     94
129     call_imm     push_imm            @     push_imm  extern_call     94
89             @     push_imm  extern_call            ;            ;     78
49             ;     call_imm     push_imm            @     push_imm     78
202     push_imm  extern_call            ;            ;           r>     76
119     call_imm     push_imm            -     call_imm     push_imm     76
65            ==   bfalse_imm     call_imm     push_imm            -     76
38             ;           ==   bfalse_imm     call_imm     push_imm     76
100   bfalse_imm     call_imm     push_imm            -     call_imm     76
36             ;            ;           r>          inc           >r     76
149  extern_call            ;            ;           r>          inc     76
32             ;            *     push_imm            +            ;     76
186     push_imm            ;           ==   bfalse_imm     call_imm     76
25             -     call_imm     push_imm            ;            *     76
174     push_imm            +            ;     call_imm     push_imm     76
18             +            ;     call_imm     push_imm            @     76
10             *     push_imm            +            ;     call_imm     76
178     push_imm            -     call_imm     push_imm            ;     76
199     push_imm     call_imm     push_imm            @     push_imm     17
58             ;     push_imm     call_imm     push_imm            @     12
40             ;           >r           >r       rcopy2            >     11
219       rcopy2            >   bfalse_imm           r>           r>     11
68             >   bfalse_imm           r>           r>         drop     11
74            >r           >r       rcopy2            >   bfalse_imm     11
188     push_imm            ;           >r           >r       rcopy2     11
160     jump_imm       rcopy2            >   bfalse_imm           r>     11
77            >r       rcopy2            >   bfalse_imm           r@     11
108   bfalse_imm           r>           r>         drop         drop     11
198     push_imm     call_imm     push_imm            ;           >r     11
126     call_imm     push_imm            ;           >r           >r     11
71             >   bfalse_imm           r@     push_imm            !      8
166     push_imm            !     push_imm     call_imm     push_imm      8
141         drop           r>          inc           >r     jump_imm      8
139         drop         drop           r>          inc           >r      8
214           r>           r>         drop         drop           r>      8
6              !     push_imm     call_imm     push_imm            ;      8
217           r@     push_imm            !     push_imm     call_imm      8
111   bfalse_imm           r@     push_imm            !     push_imm      8
210           r>         drop         drop           r>          inc      8
206     push_imm  extern_call            ;     push_imm     call_imm      6
155  extern_call            ;     push_imm     call_imm     push_imm      6
91             @     push_imm  extern_call            ;     call_imm      6
205     push_imm  extern_call            ;     call_imm     push_imm      6
92             @     push_imm  extern_call            ;     push_imm      6
227         swap            @         swap            !            ;      4
200     push_imm     call_imm         swap            @         swap      4
133     call_imm         swap            @         swap            !      4
90             @     push_imm  extern_call            ;   bfalse_imm      4
207     push_imm     push_imm     call_imm         swap            @      4
105   bfalse_imm     push_imm     call_imm     push_imm            @      3
136         drop         drop            ;     push_imm     call_imm      3
195     push_imm            @     push_imm            @     call_imm      3
209           r>         drop         drop            ;     push_imm      3
47             ;   bfalse_imm     push_imm     call_imm     push_imm      3
204     push_imm  extern_call            ;   bfalse_imm     push_imm      3
213           r>           r>         drop         drop            ;      3
151  extern_call            ;   bfalse_imm     push_imm     call_imm      3
134         drop            ;     push_imm     call_imm     push_imm      3
153  extern_call            ;     call_imm     push_imm     call_imm      3
95             @         swap            !            ;     push_imm      3
130     call_imm     push_imm     call_imm     push_imm            ;      3
50             ;     call_imm     push_imm     call_imm     push_imm      3
29             /           r>            +            ;     push_imm      2
13             *         swap          dup           >r            -      2
73            >r            -     call_imm     push_imm            ;      2
26             -     call_imm     push_imm            ;            /      2
59             ;     push_imm     push_imm     call_imm         swap      2
192     push_imm            @     call_imm     push_imm            *      2
34             ;            /           r>            +            ;      2
184     push_imm            ;            /           r>            +      2
229         swap          dup           >r            -     call_imm      2
169     push_imm            *         swap          dup           >r      2
82             @     call_imm     push_imm            *         swap      2
152  extern_call            ;     call_imm     push_imm            @      2
194     push_imm            @     push_imm            /     push_imm      2
225         swap            !            ;     push_imm     push_imm      2
142          dup           >r            -     call_imm     push_imm      2
117     call_imm     push_imm            *         swap          dup      2
208           r>            +            ;     push_imm            !      2
88             @     push_imm            @     call_imm     push_imm      2
123     call_imm     push_imm            ;            /           r>      2
4              !            ;     push_imm     push_imm     call_imm      2
203     push_imm  extern_call            ;   bfalse_imm            ;      1
181     push_imm            ;           !=   bfalse_imm     jump_imm      1
8              %     push_imm           ==   bfalse_imm     call_imm      1
7             !=   bfalse_imm     jump_imm            ;     push_imm      1
180     push_imm            /     push_imm     call_imm     push_imm      1
185     push_imm            ;            <   bfalse_imm     push_imm      1
201     push_imm  extern_call            ;            ;     push_imm      1
5              !     push_imm            @     push_imm            @      1
193     push_imm            @     push_imm            %     push_imm      1
222         swap            !            ;     call_imm     push_imm      1
189     push_imm           ==   bfalse_imm     call_imm     push_imm      1
223         swap            !            ;     push_imm            @      1
190     push_imm            @     call_imm     call_imm     push_imm      1
224         swap            !            ;     push_imm     call_imm      1
2              !            ;     push_imm     call_imm          dup      1
197     push_imm     call_imm          dup            @          inc      1
3              !            ;     push_imm     call_imm     push_imm      1
148  extern_call            ;            ;     push_imm     call_imm      1
179     push_imm            /     push_imm            @     push_imm      1
53             ;     push_imm            !            ;     push_imm      1
46             ;   bfalse_imm            ;     push_imm            @      1
48             ;     call_imm     push_imm            ;           !=      1
106   bfalse_imm     push_imm     push_imm     call_imm         swap      1
104   bfalse_imm     jump_imm            ;     push_imm     call_imm      1
101   bfalse_imm     call_imm     push_imm     call_imm     push_imm      1
99    bfalse_imm            ;     push_imm            @     push_imm      1
98            @b            ;          dup     call_imm     push_imm      1
51             ;     call_imm     push_imm     push_imm     call_imm      1
52             ;          dup     call_imm     push_imm            ;      1
94             @         swap            !            ;     call_imm      1
87             @     push_imm            @     call_imm     call_imm      1
1              !            ;     push_imm            @     push_imm      1
86             @     push_imm            /     push_imm     call_imm      1
85             @     push_imm            /     push_imm            @      1
84             @     push_imm            %     push_imm           ==      1
83             @          inc         swap            !            ;      1
54             ;     push_imm            !     push_imm            @      1
80             @     call_imm     call_imm     push_imm            ;      1
55             ;     push_imm            @     push_imm            %      1
56             ;     push_imm            @     push_imm            @      1
57             ;     push_imm     call_imm          dup            @      1
63             <   bfalse_imm     push_imm     push_imm     call_imm      1
114     call_imm          dup            @          inc         swap      1
120     call_imm     push_imm            ;           !=   bfalse_imm      1
19             +            ;     push_imm            !            ;      1
157          inc         swap            !            ;     push_imm      1
176     push_imm            +           @b            ;          dup      1
20             +            ;     push_imm            !     push_imm      1
22             +           @b            ;          dup     call_imm      1
27             /     push_imm            @     push_imm            /      1
28             /     push_imm     call_imm     push_imm            @      1
167     push_imm            %     push_imm           ==   bfalse_imm      1
165     push_imm            !     push_imm            @     push_imm      1
164     push_imm            !            ;     push_imm     call_imm      1
30             ;           !=   bfalse_imm     jump_imm            ;      1
158     jump_imm            ;     push_imm     call_imm     push_imm      1
154  extern_call            ;     call_imm     push_imm     push_imm      1
124     call_imm     push_imm            ;            <   bfalse_imm      1
150  extern_call            ;   bfalse_imm            ;     push_imm      1
66            ==   bfalse_imm     call_imm     push_imm     call_imm      1
35             ;            ;     push_imm     call_imm     push_imm      1
145          dup     call_imm     push_imm            ;            <      1
37             ;            <   bfalse_imm     push_imm     push_imm      1
143          dup            @          inc         swap            !      1
132     call_imm     push_imm     push_imm     call_imm         swap      1
131     call_imm     push_imm     call_imm     push_imm            @      1
128     call_imm     push_imm            @     push_imm            @      1
127     call_imm     push_imm            @     push_imm            /      1
0              !            ;     call_imm     push_imm            ;      1